apiVersion: apps/v1
kind: Deployment
metadata:
  name: publications-service
spec:
  replicas: 1
  selector:
    matchLabels:
     pod-name: publications-service
  template:
    metadata:
      labels:
        pod-name: publications-service
    spec:
      containers:
      - name: publications-service
        image: "docker.io/mightyfoxx/osiris_publications-management:latest"
        imagePullPolicy: Always
        ports:
        - name: http
          protocol: TCP
          containerPort: 8000
        env:
          - name: DEPLOYMENT_MODE
            value: PROD
          - name: DATABASE_URL
            value: mongodb://mongo-svc.default.svc.cluster.local/
          - name: COLLECTION_NAME
            value: publications
          - name: DB_NAME
            value: publication-service
          - name: TRENDTRACKER_URL
            value: http://trend-tracker-svc.default.svc.cluster.local
          - name: NFT_URL
            value: http://nft-generation-svc.default.svc.cluster.local
          - name: NFT_PORT
            value: "8900"
          - name: TRENDTRACKER_PORT
            value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"