apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-tracker
spec:
  selector:
    matchLabels:
      app: trend-tracker # has to match .spec.template.metadata.labels
  replicas: 1
  template:
    metadata:
      labels:
        app: trend-tracker # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: trend-tracker
        image: "docker.io/mightyfoxx/osiris_trend-tracker:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        - name: VOLUME_PATH
          value: "data/trend-data"
        - name: PUBLICATION_SVC_URL
          value: "publications-svc.default.svc.cluster.local"
        - name: PUBLICATION_SVC_PORT
          value: "8000"
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "special-worker"
        effect: "NoSchedule"