apiVersion: v1
kind: Service
metadata:
  name: trend-tracker-svc
  labels:
    app: trend-tracker
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    app: trend-tracker