apiVersion: v1
kind: Service
metadata:
  name: trend-tracker
  labels:
    app: trend-tracker
spec:
  ports:
  - port: 8080
    name: trend-tracker
  clusterIP: None
  selector:
    app: trend-tracker