apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deployment
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 1
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: mightyfoxx/osiris_krakend:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        command: [ "krakend" ]
        args: [ "run", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]
        env:
        - name: KRAKEND_PORT
          value: "8080"